/*
    Quimblos

    [Reserved words]

    true
    false
    device
    sleep
    log
    stop
    error
    if
    else
    end
    break
    continue
    loop
    'u8','i8','b8','u16','u8xy','i16','i8xy','u32','u16xy','u8xyzw','i32','i16xy','i8xyzw','float32','string'

    [Reserved characters]

    @ -> runner directives
    # -> hexcode
    '" -> string definition
    =+-*[/]%>< -> arithmetics
*/

grammar ::= blank? ((comment | directive | statement) blank?)+
statement ::= flow_statement | assignment | declaration | runner_statement

/*
    Comments
*/

comment ::= '//' [#x20-#xD7FF]* eol?

/*
    Runner Directives
    
    - @device [word]
*/

directive ::= directive_device
directive_device ::= '@' kw_device ws word eol

flow_statement ::= if_statement | if_else_statement | loop_statement | while_statement | break_statement | continue_statement

/*
    If/Else/Break Statement

    - if var > 3:
      ...
      end
    - if var > 3:
      ...
      else:
      ...
      end
*/

if_statement ::= kw_if ws comparison ws ':' eol grammar kw_end eol
if_else_statement ::= kw_if ws comparison ws ':' eol grammar kw_else ws ':' eol grammar kw_end eol

/*
    Loop Statement

    - loop:
      ...
      end
*/

loop_statement ::= kw_loop ':' eol grammar kw_end eol

/*
    While Statement

    - while var > 3:
      ...
      end
*/

while_statement ::= kw_while ws comparison ws ':' eol grammar kw_end eol

/*
    Break/Continue Statement
*/
break_statement ::= kw_break eol
continue_statement ::= kw_continue eol

/*
    Assignments

    - var = 3 \n
    - var += 3 \n
*/

assignment ::= variable ws op_art? op_assign ws primitive eol

/*
    Declarations

    - u8 acc
*/

declaration ::= kw_type ws word eol

/*
    Runner Statements

    - sleep 1000
    - log "something happened"
    - log 1 "something happened with code 1"
    - stop "something happened"
    - stop 1 "something happened with code 1"
    - error "something happened"
    - error 1 "something happened with code 1"
*/

runner_statement ::= sleep_statement | log_statement | stop_statement | error_statement

sleep_statement ::= kw_sleep ws uint eol
log_statement ::= kw_log (ws uint)? ws string eol
stop_statement ::= kw_stop (ws uint)? ws string eol
error_statement ::= kw_error (ws uint)? ws string eol

/*
    Arithmetics and Comparisons
    - var + 3
    - var < 3
*/
art ::= variable ws op_art ws primitive
comparison ::= variable ws op_compare ws primitive

/*
    Special Primitives

    - var | device.port
    - word
*/

variable ::= word ('.' word)?
word ::= letter (letter | digit)*

/*
    Primitives

    - true | false
    - #00120343
    - -12.34
    - 1234
    - "some text"
*/

primitive ::= boolean | hexcode | float | intger | string

boolean ::= kw_true | kw_false
hexcode ::= '#' [a-fA-F0-9]+
float ::= ('-' ws?)? ((digit+ '.' digit+)|(digit+ '.')|('.' digit+))
int ::= ('-' ws?)? digit+
uint ::= digit+

string ::= '"' (char | ws)* '"'
char ::= letter | digit | special_char

/*
    Keywords
*/

kw_true ::= 'true'
kw_false ::= 'false'
kw_device ::= 'device'
kw_sleep ::= 'sleep'
kw_log ::= 'log'
kw_stop ::= 'stop'
kw_error ::= 'error'
kw_if ::= 'if'
kw_else ::= 'else'
kw_end ::= 'end'
kw_break ::= 'break'
kw_continue ::= 'continue'
kw_loop ::= 'loop'

kw_type ::= 'u8' | 'i8' | 'b8' | 'u16' | 'u8xy' | 'i16' | 'i8xy' | 'u32' | 'u16xy' | 'u8xyzw' | 'i32' | 'i16xy' | 'i8xyzw' | 'float32' | 'string'

op_assign ::= '='

op_art ::= op_sum | op_sub | op_mult | op_div | op_mod
op_sum ::= '+'
op_sub ::= '-'
op_mult ::= '*'
op_div ::= '/'
op_mod ::= '%'

op_compare ::= op_eq | op_neq | op_gt | op_lt | op_gteq | op_lteq
op_eq ::= '=='
op_neq ::= '!='
op_gt ::= '>'
op_lt ::= '<'
op_gteq ::= '>='
op_lteq ::= '<='

/*
    Lexical
*/

letter ::= [a-zA-Z] | [#xC0-#xFF] /* Latin-1 */
digit ::= [0-9]
special_char ::= [-._/]

blank ::= [#x20#x09#x0A#x0D]+ /* Space | Tab | \n | \r */
eol ::= ws* [#x0A#x0D#x00]+ /* \n | \r | \0 */
ws ::= [#x20#x09]+ /* Space | Tab */

